# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
#  pod 'Kanna'
  pod "SwiftyJSON"
  pod 'Alamofire'
  pod 'Eureka', '~> 2.0.1'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'SwiftyVIPER'
  pod 'RxCocoa'
  pod 'Kingfisher'
#  pod 'BadgeSwift', '~> 4.0'
  pod 'Badgeable'



# Pods for testt

end
